# Generated by Django 3.0.8 on 2020-08-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guidelist',
            fields=[
                ('guide_sn', models.AutoField(primary_key=True, serialize=False)),
                ('guide_title', models.CharField(max_length=100)),
                ('guide_description', models.TextField()),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='guidelines/images')),
            ],
        ),
    ]
