# Generated by Django 3.0.8 on 2020-08-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='support',
            fields=[
                ('support_sn', models.AutoField(primary_key=True, serialize=False)),
                ('support_title', models.CharField(max_length=20)),
                ('image', models.ImageField(default='', upload_to='SCAS/images')),
            ],
        ),
    ]
