# Generated by Django 3.0.8 on 2020-08-29 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCAS', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='support',
            new_name='Supports',
        ),
    ]
