# Generated by Django 3.0.8 on 2020-08-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='training',
            fields=[
                ('training_sno', models.AutoField(primary_key=True, serialize=False)),
                ('training_title', models.CharField(max_length=50)),
                ('training_description', models.TextField()),
                ('image', models.ImageField(default='', upload_to='trainings/images')),
            ],
        ),
    ]
